- Mergin/plugin.py
- Mergin/sync_dialog.py
- Mergin/ui/ui_sync_dialog.ui
- Mergin/utils.py
This adds a dialog for download and synchronization that shows progress and can be cancelled. It should not happen anymore that the whole QGIS will become unresponsive.
Fixes #2
Fixes #27
Needs https://github.com/lutraconsulting/mergin-py-client/pull/44
> Integrate async upload/download

- Mergin/plugin.py
- Mergin/sync_dialog.py
Mergin plugin will report full traceback, not just exception converted to string, which does not say much (see #132)
Note: this does not fix the underlying issue of #132, only improves error reporting.
> Better reporting of unhandled exceptions (fixes #132)

- scripts/package.sh
Fix #126
As far as my investigation goes, that weird bug was caused by the fact that the 'deps' directory was getting recognized as "namespace package" in Python's import system because it does not have __init__.py file. That is somehow breaking QGIS plugin unloading mechanism but I didn't
look further what exactly is causing the issue.
Python import system: https://docs.python.org/3/reference/import.html
Namespace packages: https://www.python.org/dev/peps/pep-0420/
> Fix KeyError: 'Mergin.mergin' when closing QGIS

- Mergin/sync_dialog.py
Closes https://github.com/lutraconsulting/mergin-py-client/issues/88 - it was reported for Mergin Python client but actually fixed in the Mergin plugin code.
> Fixed Python deprecation warnings about implicit float/int conversions

- Mergin/metadata.txt
Closes #230
We use `QgsMapLayerType` enum which is available only for QGIS 3.10+
> Bumped minimum QGIS version for the plugin to 3.10

- Mergin/plugin.py
- Mergin/utils.py
It is a part of a fix for #186 - https://github.com/lutraconsulting/mergin-py-client/pull/91
> Add global Mergin client log to user-submitted logs

- Mergin/plugin.py
Remote project browser items actually need the open_project() method - once the project is downloaded it may be also open - and it should be ideally done before refreshing the group item, so before the remote project item would turn into a local one.
> Fixed remote project item - opening a downloaded project.

- Mergin/plugin.py
This fixes fetching more items in the Explore group. There was invalid number of already fetched projects calculated and the Fetch more browser item was hidden well before a user fetch all the projects from the group.
We no longer depopulate the group after a page of projects is fetched, so we need to calculate fetched projects number in a different way.
> Fix fetching more items in Explore group

- .github/workflows/packages.yml
- README.md
Add CI support to generate Mergin QGIS Plugin. The pygeodiff libraries are included, but NOT patched to use QGIS sqlite library, so most probably it plugin will not load in QGIS
> ci for packaging (part-1 no fixes for libs rpaths)

- .github/workflows/packages.yml
Remove the internal sqlite3 dependency from pygeodiff on linux (sqlite3 will be used from qgis install)
Refs #261
> [CI] Packaging for linux

- Mergin/create_project_wizard.py
- Mergin/metadata.txt
- Mergin/utils.py
Fixes #273 - do not rewrite GeoTiffs 
Fixes #277 - added a check for tree node layers validity - invalid layers are kept as is by default - they might be valid layers in a specific environment only.
> Packaging fixes

- Mergin/plugin.py
**PR REQUIRES NEW VERSION OF MERGIN_PY_CLIENT!**
This PR adds action required banner to plugin. 
`/v1/user/service` endpoint is used to find out if the banner should be visible based on `action_required` key. API call has been added to mergin py client.
Banner is shown inside Qgis message bar as error message without timer. It is shown each time user logs in or starts QGIS while being logged in automatically.  
Screenshots:
> Note: latter message grammar errors will be fixed on Mergin side
> Add attention banner

- Mergin/metadata.txt
- Mergin/plugin.py
- Mergin/project_settings_widget.py
- Mergin/ui/ui_project_config.ui
This PR adds a new tab in projects properties related to mergin project. Currently it enables to configure selective sync for Input. If open project is not a mergin project, this option is disabled.
Needs update to QGIS 3.16
Closes #282
> Add option to configure selective sync

- Mergin/projects_manager.py
PR fixes the issue with mergin server name saved in settings. In case that original server name contained trailing backslash and then server URL was updated without it, project would fail complaining about different servers.
Server names are now compared always without trailing backslash.
closes #285
> Remove trailing backslash when comparing mergin servers names

- Mergin/ui/ui_project_config.ui
Opening the project properties in debug builds of qgis is hitting an assert leading to a crash:
```
Fatal: ASSERT failure in QgsProjectProperties::checkPageWidgetNameMap(): "QgisApp::projectPropertiesPagesMap() is outdated, please update. Mergin should be QWidget not Mergin", file /home/uclaros/dev/cpp/QGIS/src/app/qgsprojectproperties.cpp, line 2637
```
Fixes #336
> Avoid hitting assert in qgsprojectproperties

- Mergin/projects_manager.py
Stop sync if conflicts were created and show warning with the list of conflicting copies. Reword warning message to point user to documentation.
Fixed #330.
> Stop sync if conflicts were created and reword corresponding message (fix #330)

- Mergin/project_status_dialog.py
- Mergin/projects_manager.py
Implement additional checks and logic for handling unfinished pull, as described in #327.
Following workflow was implemented:
1. When sync initiated plugin checks whether previous pull was completed successfully. If unfinished pull was found we try to finish it (if project is opened in QGIS it will be closed beforehand and then re-opened). As finishing previous pull means creation of conflicted copies, sync is stopped and user asked to check conflicts to prevent data loss. 
2. If project is in clean state first phase of sync (pull) started
3. Pull might fail and project will end up in the unfinished pull state. So we close project and try to finish pull. At this point sync will stop, because on success we will have conflict files and on failure we still have unfinished pull.
4. If pull …
> Handle unfinished pull

- Mergin/processing/algs/create_report.py
- Mergin/utils.py
Reporting code in the Mergin Python client can raise ClientError. Handle it in the Processing tool and gracefully fail instead of showing traceback.
> handle exception which may be raised when creating report

- Mergin/plugin.py
On Windows when QGIS project is cleared OS needs some time to release lock on open files. So when we try to remove files they still might be locked. As a result removing local project copy will file. To avoid this we add a small delay before attempt to remove Mergin project files.
Fixes #352.
> Fix "Remove locally" functionality (fix #352)

- Mergin/projects_manager.py
As described in #351 when user who is not an owner of the organization tries to sync project of the organization they get error. It happens because plugin relies on the `access` field of the project information to determine whether user has write permissions on a given project. However `access` field is taken from the explicit project permissions, while invited to the organization users get access via this organization.
In order to overcome this issue we need to check write access also by using `permissions` field, as this field is evaluated with respect to namespace.
Also need to fix the same issues in the Python client lutraconsulting/mergin-py-client#130
Fixes #351
> take into account namespace permissions to get user privileges (fix #351)

- Mergin/plugin.py
Clearing project does not fires signals which trigger buttons state update. So we have to fire signal manually.
Fixes #359.
> disable sync and status buttons when project was removed locally (fix #359)

- Mergin/help.py
- Mergin/plugin.py
- Mergin/project_status_dialog.py
- Mergin/projects_manager.py
- Mergin/test/test_help.py
- Mergin/ui/ui_status_dialog.ui
- Mergin/validation.py
Show project status dialog before sync, so users can revise changes and be aware of any possible misconfigurations/changes which may break their project. Both "Sync" and "Status" toolbar buttons and context menu item will open the Project Status dialog. When invoked via "Sync" button the Project Status dialog will have a "Sync" button to start synchronization, otherwise only "Close" button will be shown.
Improve status dialog UI by:
- saving/restoring its size and position
- dropping tabs and making validation results more visible to user. If there are no warnings, validation results widget will be hidden to save space and avoid confusion.
- using message bar at the top of the dialog instead of the plain label at the bottom to display messages
- use rich text widget for validation …
> Improve validation/sync workflow and status dialog overhaul

- Mergin/processing/algs/create_report.py
If end version is not set assume that the latest project version should be used as end version when creating report.
Requires lutraconsulting/mergin-py-client#132
> make end version parameter optional in the reporting tool (fix #365)

- Mergin/utils.py
Newly added GPKG files does not have a base file until the first sync is completed, so we can't check their schema for changes.
Fixes #376.
> don't check schema changes in newly added files (fix #376)

- Mergin/test/test_validations.py
- Mergin/utils.py
- Mergin/validation.py
This is a workaround for the case when field or table names contain caret return character and cause broken JSON output from geodiff.
> drop caret returns from JSON before reading it (fix #378)

- Mergin/test/test_validations.py
- Mergin/utils.py
- Mergin/validation.py
Adds more validations, this time for relations:
- check that project relations and value relations don't use GPKG primary key column as referenced/referencing column
- check that referenced/referencing columns contain only unique values
- check that referenced layer in value relation present in the QGIS project.
Fixes #291 and #296.
> Relation validations

- Mergin/project_settings_widget.py
- Mergin/ui/ui_project_config.ui
Adds dropdown to Mergin project settings dialog with the following options: "Original", "High", "Medium" and "Low". By default "Original" setting is used to keep backward compatibility.
Refs lutraconsulting/input/issues/841.
> add photo quality setting to mergin project properties

- Mergin/validation.py
Relying on the layer source is not optimal, better to use layer id.
Fixes #393.
> fix child layer detection in value relation validation (fix #393)

- Mergin/validation.py
If non GPKG layers are used in relations check for primary keys fails. This PR fixes it by skipping such check for non-GPKG layers.
Fixes #401.
> don't check for primary keys for non-GPKG layers (fix #401)

- Mergin/sync_dialog.py
Gracefully handle case when sync job was not created yet, this might happen if one cancels sync immediately after starting it.
Fixes #405.
> catch errors caused by non-existent sync job when operation is cancelled (fix #405)

- Mergin/projects_manager.py
Validate project URL against new and old server URL before syncing.
Fixes #409.
> consider new and old server URL when checking for project server (fix #409)

- Mergin/test/test_utils.py
- Mergin/test/test_validations.py
- Mergin/validation.py
Check that data-defined default root uses `@project_home` and similar variables to create a path relative to project location.
Refs #278 and https://github.com/lutraconsulting/input/issues/1611.
> More validations for attachment widget configuration

- Mergin/diff.py
- Mergin/diff_dialog.py
- Mergin/images/tabler_icons/file-diff.svg
- Mergin/images/tabler_icons/file-plus.svg
- Mergin/images/tabler_icons/folder-plus.svg
- Mergin/plugin.py
- Mergin/processing/algs/create_diff.py
- Mergin/processing/algs/extract_local_changes.py
- Mergin/processing/postprocessors.py
- Mergin/processing/provider.py
- Mergin/project_status_dialog.py
- Mergin/ui/ui_diff_viewer_dialog.ui
- Mergin/ui/ui_status_dialog.ui
Add an action "Show local changes" to the layer context menu toolbar button to open a "Diff viewer" dialog where one can examine local changes made in the project
If there are no changes in the project, a message bar will be shown, telling that there are no changes which can be visualised.
The "Changes Viewerer" dialog provides a tab-based UI, where each tab represents a local layer with changes. Changes in the layer will be shown on canvas and in the table form (splitted with a splitter).
Toolbar buttons allow user:
- toggle display of project layers (on by default)
- zoom to full extent of the changes layer
- zoom to selected features of the changes layer
- add currently displayed or all changes layers to project
All changes layers have styling applied and conditional formatting of the …
> Visualisation of local changes

- Mergin/project_settings_widget.py
- Mergin/ui/ui_project_config.ui
- Mergin/validation.py
Add Input snapping settings to the QGIS project setting
Also add a validation for the case when "Follow QGIS snapping" mode is selected but snapping is not enabled in the project.
> Snapping settings

- Mergin/images/default/tabler_icons/explore.svg
- Mergin/images/default/tabler_icons/search.svg
- Mergin/plugin.py
- Mergin/project_selection_dialog.py
- Mergin/projects_manager.py
- Mergin/ui/ui_select_project_dialog.ui
- Mergin/utils.py
Added _Find project_ and _Explore public projects_ dialogs, accessible via the browser's context menus.
For EE/CE:
For old servers:
Find projects looks like this:
The switch workspaces text is only visible is there are more workspaces available.
Explore public projects looks like this:
> find project / explore public projects

- Mergin/plugin.py
- Mergin/project_selection_dialog.py
- Handles an exception caused by a broken local project
- Use newest api for paginated results (`only_public=true`, `order_params=workspaces_asc`)
- Use QgsFilterLineEdit.setShowSpinner() instead of global cursor override while fetching results. It adds the spinner to the right end of the line edit widget and looks like this:
https://user-images.githubusercontent.com/11358178/215084035-a0551f69-b481-41a6-b202-b2c8ca1e5f6d.mp4
> Workspaces QA fixes

- Mergin/attachment_fields_model.py
- Mergin/project_settings_widget.py
- Mergin/test/test_help.py
- Mergin/test/test_packaging.py
- Mergin/test/test_utils.py
- Mergin/test/test_validations.py
- Mergin/ui/ui_project_config.ui
- Mergin/utils.py
Add UI to configure expression-based photo names to the project properties dialog. If expression for a field is set, Input will use it to rename photos.
> Expression-based names for photos

- Mergin/utils.py
Since QGIS 3.31 "vectortile" provider name was changed to "mbtilesvectortiles". To keep MBTiles packagin functional in latest QGIS versions we need to check provider name against both variants.
> handle change of the vector tiles provider name in latest QGIS

- Mergin/projects_manager.py
If project removed manually (outside of QGIS) an attempt to check project status results in a Python error. Better to catch an exception and show more friendly error dialog.
Fixes #263.
> show error message when trying to get status of removed project (fix #263)

- Mergin/plugin.py
Text changed to "Double-click to configure..." and double-click handler added (opens plugin's configuration window).
fix https://github.com/MerginMaps/qgis-mergin-plugin/issues/508
> reword "not configured" message and make it clickable (fix #508)

- Mergin/plugin.py
- Mergin/remove_project_dialog.py
- Mergin/ui/ui_remove_project_dialog.ui
Replace simple question message box with a custom dialog where user needs to enter project name to comfirm its removal from the server
Fixes #128.
> ask user to type project name to confirm its removal from the server (fix #128)

- Mergin/projects_manager.py
- Mergin/sync_dialog.py
- Mergin/utils.py
When the project is downloaded for the first time and the download crashes during this process mergin log is removed, making it much harder to debug and fix possible issues. This PR adds an option to the error dialog to send log to the developers. Requires Python client with https://github.com/MerginMaps/mergin-py-client/pull/182.
Refs https://app.clickup.com/t/862k79n4m
> add option to submit logs when download fails

- Mergin/images/default/tabler_icons/revert-changes.svg
- Mergin/images/white/tabler_icons/revert-changes.svg
- Mergin/project_status_dialog.py
- Mergin/projects_manager.py
- Mergin/ui/ui_status_dialog.ui
Fixes #281 
Requires updated to mergin-client with the `reset_local_changes()`.
> add reset local changes

- Mergin/test/test_validations.py
- Mergin/validation.py
Raster  MBTiles are loaded with WMS provider and we need additional check whether this layer comes from local or remote source.
Fixes #540.
> do not show local mbtiles as not available offline (fix #540)

- .github/workflows/packages.yml
- Mergin/project_status_dialog.py
- Mergin/projects_manager.py
- Mergin/utils.py
- Mergin/validation.py
- docs/dev-docs.md
resolves #581 
Validate local changes for editor permission and give possibility to reset not allowed changes to be able to sync allowed changes.
Latest validation messages preview:
> Editor validation gh#581

- .github/workflows/packages.yml
To (hopefully) fix the CI. If it won't work, let's revert back to version 3 and kill dependabot 👼🏻 
EDIT
- Reverted back to`v3`, there are several braking changes in the `v4`. We will eventually migrate, but let's keep it for later, see https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new
> Revert actions to @v3

- Mergin/create_project_wizard.py
Strip spaces from Project Name in Create new project window.
Fix #552
> strip trailing whitespace from project name

- .github/workflows/packages.yml
- .github/workflows/run-test.yml
**packaging**  
Bump version of mergin client and geodiff to latest in the packaging workflow
**auto test** 
Bump version of mergin client to `master` in the testing workflow
This PR solve the issue in the short term since there was a python api client release but  I think we should do the packaging on master as well ,  and have a separate workflow for release using only latest released version of dependancies
> Bump version of mergin client and geodiff in actions workflow

- .github/workflows/packages.yml
- .github/workflows/run-test.yml
- docs/dev-docs.md
Changes all previous reference to the current repository to `python-api-client` instead of `mergin-py-client`
Most of the changes are in the actions
No functional changes, but let's wait for the tests in case
> Cleanup reference to previous repository name of python-api-client

- .github/workflows/packages.yml
- .github/workflows/run-test.yml
This PR enable a workflow to be triggered manually with custom inputs using `workflow_dispatch` event.
The packages.yml and run-test.yml workflow are currently supported 
This PR reuse the same workflow used when a commit is  pushed and should remain compatible 
Currently we support the following argument(inputs)
* `PYTHON_API_CLIENT_VER` : For python-api-client you can choice any release, tag or branch
* `GEODIFF_VER`: For geodiff only the version uploaded on  PyPi are supported  
To note, you  can't trigger the workflow from the github web interface since it's not yet on the default branch, to test from the  cli interface, use the following command e.g:
For packaging: 
```
gh workflow run "Build Mergin Plugin Packages" --ref workflow-dispatch -f PYTHON_API_CLIENT_VER="master"
```
For …
> Enable packaging and test workflows to be triggered mannually with custom inputs  

- Mergin/projects_manager.py
- Mergin/utils.py
This PR improve the dialog error given to user when trying to create a project and sync project. Instead of giving a dump of the server error we display only the part that matter to the users
So far we handle 
* Project with an already existing name 
* projects limit hit error
* Storage limit error
* Another syncing process running
This PR  also relies on another PR in the mergin python api client (see : MerginMaps/python-api-client/pull/209 )
resolve #599 
resolve #561
Before: 
<br>
After:
> Better dialog error when trying to create a project with an already existing name and the projects limit hit error.

- Mergin/create_project_wizard.py
- scripts/deploy_win.py
this is mainly for support agents who need to find the right one in a list of more than 100 of them
> Sort workspaces list in new project wizard

- Mergin/metadata.txt
- Mergin/ui/ui_project_config.ui
- Mergin/utils.py
- Mergin/validation.py
Cleanup reference to the old name of the Mergin Maps mobile app
The old name was used used :
* in project settings
* Status dialog
* And some comments in the code
Fix #623
> Cleanup reference to the old Mergin Map mobile app name in the plugin

- Mergin/create_project_wizard.py
- Mergin/plugin.py
- Mergin/projects_manager.py
- Mergin/utils.py
The qgis project was not reloading after a sync on windows when there was only change to the .qgz file
This happened because ` QgsProject.instance().fileName()` &` QgsProject.instance().absolutePath() `returned unix-style path even on windows. This behavior mismatch with the return of e.g `os.path.join` in python. 
This PR fix the is by adding an extra os.path.normpath
Fix #617
> Fix 617: Reload project following sync of updated .qgz file on windows

- Mergin/clone_project_dialog.py
- Mergin/collapsible_message_box.py
- Mergin/configuration_dialog.py
- Mergin/create_project_wizard.py
- Mergin/plugin.py
- Mergin/project_settings_widget.py
- Mergin/project_status_dialog.py
- Mergin/projects_manager.py
- Mergin/remove_project_dialog.py
- Mergin/utils.py
This PR rename deprecated enum and method in qt5 and that will be removed in qt6. This should make the plugin mostly compatible when QGIS finally does switch to a newer version of qt.
See : https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/
Ideally from now on we should  write code compatible with qt6
> Rename deprecated enum and method in qt5 to qt6

- Mergin/plugin.py
This PR contain two cleanup
* Remove useless "post_login" and "mc.user_service()" since user_service was deprecated and return http 400 the `post_login`  function didn't do anything
see https://github.com/MerginMaps/server-private/blob/7edf64b43b04bf017c8c555f913f6d8c3b0d7441/server/src/service/api.yaml#L42
* Handle new ClientError from `mc.workspace_service`
Rely on https://github.com/MerginMaps/python-api-client/pull/224
> Cleanup useless function and error handling 

- Mergin/processing/algs/create_diff.py
- Mergin/processing/algs/extract_local_changes.py
- Mergin/ui/ui_clone_project.ui
- Mergin/ui/ui_config.ui
- Mergin/ui/ui_sync_dialog.ui
Fix use of old names of Mergin Maps components in various places.
Fixes #572.
> Fix component names

- Mergin/configure_sync_wizard.py
- Mergin/plugin.py
- Mergin/projects_manager.py
- Mergin/ui/ui_gpkg_selection_page.ui
Use UK English spelling "synchronize" → "synchronise".
Fixes #579.
> use UK spelling (fix #579)

- .github/workflows/packages.yml
Bump upload-artifact and download-artifact action to v4.
Some changes were required in the PR because in  the V4, artifact are immutable once created. You can't incrementally add file to an artifact anymore, we have to use the `actions/upload-artifact/merge@v4` see https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#merging-multiple-artifacts
> Bump upload-artifact and download-artifact action to v4

- Mergin/version_viewer_dialog.py
Fix crash when changing layer in the history viewer because of out of sync issue between the state application and the UI
> Fix crash when changing layer in history viewer on some state

- Mergin/diff.py
Fix updated geometry not highlighted in the attribute table,
The old geometry was indeed calculated but never assigned to the column field in the  QgsFeature
There is a bit of duplicated code here but I would considerate the clean up as a todo
Fix #670
> Fix updated geometry not highlighted in the attribute table

- Mergin/utils.py
When a tracking layer is enable we create a default display expression as well 
Looks like this in the mobile app
Fix #681
> Add user friendly display expression for tracking layer

- Mergin/processing/algs/download_vector_tiles.py
Small annoyance I found while trying to make a vector tiles layer available offline
The process would crash if the requested zoom level is instead only issue a simple warning and clamp the requested zoom level to the source
See before/after :
> Download Vector Tiles process, issue a warning instead of a crash if the request  zoom level is bigger than source layer zoom level

- Mergin/diff.py
Unless what the ticket said it was not because multiple layer saved in the same geopackage but because the geopackage was in a subfolder.
the search glob would only search for geopackages at the root path of the version downloaded, this PR also search recursively in the directory
Fix #685
> Fix 685: History viewer  changes visualisation not working if the geopackage was in a sub folder

- Mergin/utils.py
This PR add a warning for the user if they use a deprecated server version (< 2023). The warning popup appears when testing connection and when connecting 
We will drop support with #689 in the release afterward
> Deprecate old server version (< 2023)

- Mergin/test/test_utils.py
- Mergin/utils.py
Fix crash when adding a map sketches layer because we can't use the new fancy enum in older QGIS release.
Also add a test case for this
> Fix crash when adding map sketches on older QGIS release and add a test case

- Mergin/project_settings_widget.py
- Mergin/ui/ui_project_config.ui
- Mergin/utils.py
This PR hides the map sketches, based on the experimental flag in the plugin manager. 
if enable the map sketches shows up with the `(Experimental)` title added
if not enabled the map sketches settings don't shows up
> Hide map sketches behind the experimental plugin flag

- Mergin/configuration_dialog.py
- Mergin/create_project_wizard.py
- Mergin/projects_manager.py
- Mergin/sync_dialog.py
use the `with OverrideCursor(...):` idiom instead of relying to manual `QApplication.restoreOverrideCursor()` calls.
Use `split` diff for reviewing, as it's mostly just an indentation level change.
Fixes the stuck wait cursor reported in https://github.com/MerginMaps/qgis-plugin/issues/753#issuecomment-3077608733
> Better handling of restoring overriden cursors

- Mergin/version_viewer_dialog.py
Ugly fix to make the extent work on macos and linux
the previous fix only worked on windows but in the end, the good behavior should be the one on unix, remove once we drop support for 3.34
Fix #701
> Fix extent  in history viewer on unix

- Mergin/create_project_wizard.py
- Mergin/project_settings_widget.py
- Mergin/ui/ui_project_config.ui
- Mergin/utils.py
Add a toggle in the project configuration to sort layer either by qgis layer panel or by alphabetical order in the mobile app layer controller
See also [mobile/pull/3980](https://github.com/MerginMaps/mobile/pull/3980)
> Toggle alphabetic sort in the project

- Mergin/projects_manager.py
- Mergin/utils.py
Enhanced the "unhandled exception" dialog:
- sending diagnostic log did not work before (passed `username` instead of the client ref)
- does not redirect users to GH issue tracker, but our support instead
- submits diagnostic log and opens email client with `mailto:` in one click
- `mailto` message is preformatted, includes recipient, subject, body with the error message and a placeholder for user to enter more details about what happened
- adds optional checkbox if one does not want to share the log
- contains more UX-friendly messages
Hopefully, this should redirect most of the reports to the support team so we do not need to forward it manually ourselves.
| Old | New |
|--------|--------|
| <img width="532" height="408" alt="Screenshot 2025-09-01 at 17 00 38" …
> Adds better unhandled exception dialog during project sync
