MerginMaps/qgis-plugin

- scripts/package.sh
to include geodiff binaries for multiple platforms
> updated packaging script 

- Mergin/metadata.txt
> bump the version

- Mergin/plugin.py
added list of changes to status function
> # 61 list of changes

- Mergin/configuration_dialog.py
- Mergin/create_project_dialog.py
because QGisAuthManager and masterpassword didn't work as we expected
Is it necessarily save Configuration again to fix be done
(closes #69 )
> added username to Qgis.ini file

- Mergin/create_project_dialog.py
- Mergin/ui/ui_create_project.ui
> modified message where blank project was created

- Mergin/plugin.py
> reload project after sync if the open project was synchronized

- Mergin/utils.py
> change check if master password exist in db

- Mergin/ui/ui_create_project.ui
I changed the maximum size, I think it fixes my problem #73
> More maximum size for label

- Mergin/configuration_dialog.py
- Mergin/plugin.py
- Mergin/utils.py
> added logging errors from pyclient if were lost

- Mergin/plugin.py
> fix error message during syncing

- Mergin/configuration_dialog.py
also server change is needed
(relates #102)
> response message will be written to dialog window

- Mergin/collapsible_message_box.py
- Mergin/create_project_dialog.py
> created collapsible error message box with detail information

- Mergin/plugin.py
typical use case is to create new project from My project GroupItem
> fix missing mergin client attribute error

- Mergin/create_project_dialog.py
- Mergin/plugin.py
- Mergin/sync_dialog.py
- Mergin/ui/ui_create_project.ui
Fixes #127 
This needs https://github.com/lutraconsulting/mergin-py-client/pull/50 to work
Updated "create project with upload" to use the new sync dialog with async push of the project. Also moved the "heavy duty" code out of the dialog .py file to plugin py file where the rest of pull/push calls are done.
> Update creation of a project with an initial push to use sync dialog

- Mergin/plugin.py
> (Quick) Fix of QGIS crash on init

- Mergin/create_project_dialog.py
- Mergin/plugin.py
- Mergin/ui/ui_create_project.ui
Depends on: https://github.com/lutraconsulting/mergin-py-client/pull/69
closes #169
> Added namespace parameter for creating a new project

- Mergin/configuration_dialog.py
- Mergin/utils.py
> Add validation of URL

- Mergin/create_project_wizard.py
- Mergin/plugin.py
- Mergin/utils.py
Fixed project manager recreation after config change and cleaned settings entries for working dir.
> Config and settings fixes

- Mergin/images/FA_icons/fetch_more.svg
- Mergin/plugin.py
- Mergin/utils.py
Also fixed multiple project managers creation issue.
> Fetch projects using the paginated list endpoint

- Mergin/create_project_wizard.py
> Non spatial layers are now visible in the wizard

- Mergin/configuration_dialog.py
Fixes #229.
See also https://github.com/lutraconsulting/mergin-py-client/pull/85
> Handle URLError when testing connection settings.

- Mergin/plugin.py
- Mergin/projects_manager.py
- Mergin/utils.py
> Handle Mergin server changes

- Mergin/utils.py
> Ensure projects packaged by the wizard are set for relative paths

- Mergin/configuration_dialog.py
- Mergin/utils.py
- Mergin/validation.py
Using improvements from https://github.com/lutraconsulting/mergin-py-client/pull/89
Fixes #123
> Support for HTTP proxy server

- Mergin/project_status_dialog.py
- Mergin/projects_manager.py
Fixes #181.
For locally added files there was unwanted info in project status dialog.
> Removed unwanted "Unable to detect changes" for locally added files

- Mergin/utils.py
- scripts/deploy_win.py
Complementary fix for https://github.com/lutraconsulting/qgis-mergin-plugin/issues/123
> Fix for reading proxy settings in QGIS

- Mergin/utils.py
> Handle non-unique fid columns for packaged layers

- Mergin/plugin.py
- Mergin/projects_manager.py
> Local Mergin projects are now browser directory items

- Mergin/projects_manager.py
> Reload updated layers after sync

- Mergin/plugin.py
This PR adds duration parameter to make message not disappear after few seconds but stay there until user closes it manually.
> Make attention banner permanent

- Mergin/metadata.txt
- Mergin/plugin.py
- Mergin/processing/algs/create_report.py
- Mergin/processing/provider.py
- Mergin/utils.py
Add Processing provider to the plugin. Currently there is only single tool called "Create report" to export changesets aggregates for Mergin projects in given version range to a CSV file. Needs Mergin Python client library with lutraconsulting/mergin-py-client#127 included.
Some screenshots
> Reporting tool

- Mergin/projects_manager.py
Address review comments from #344:
- change message bar title
- move repeated code into reusable function
> Address review

- Mergin/configuration_dialog.py
- Mergin/ui/ui_config.ui
- Mergin/utils.py
- fix parsing of excluded URL's (ref https://github.com/lutraconsulting/qgis-mergin-plugin/issues/309#issuecomment-978125062)
- test credentials and report if they are invalid (fix #297)
- try to use system proxy if QGIS uses "Default proxy" (ref https://github.com/lutraconsulting/qgis-mergin-plugin/issues/309#issuecomment-982423292)
> Improve proxy handling and login UX

- Mergin/project_settings_widget.py
Restores visibility of the hidden UI elements (partially reverts 363bd035a4d9414020fdc7a134700f26b3512b9d)
> bring back UI for adjusting photo quality

- Mergin/validation.py
Port of #402 to `validation_fix_release` branch
> don't check for primary keys for non-GPKG layers (fix #401)

- Mergin/metadata.txt
- Mergin/ui/ui_config.ui
- Mergin/utils.py
- README.md
> update public server URL

- Mergin/plugin.py
Remove rebranding banner as discussed.
> drop rebranding banner

- Mergin/test/test_packaging.py
- Mergin/utils.py
> Added updating raster datasource after copying files.

- Mergin/ui/ui_config.ui
Proposal to change the tab order.
Fixes #431
> change tab order in config

- Mergin/test/test_packaging.py
- Mergin/utils.py
Support for packaging local raster and vector MBTiles
Fixes #452.
> Local MBTiles packaging

- Mergin/ui/ui_project_config.ui
- Mergin/validation.py
Fixes a couple of issues:
- #460 
- #459 and #438
> Fix validation when RelativeStorage is missing + fix doc link

- Mergin/plugin.py
Requires https://github.com/MerginMaps/mergin-py-client/pull/152
Not yet tested
> Use new api/logic for _attention needed_

- Mergin/clone_project_dialog.py
- Mergin/create_project_wizard.py
- Mergin/test/test_utils.py
- Mergin/ui/ui_project_config.ui
- Mergin/utils.py
- Mergin/validation.py
Merging master into workspaces got a conflict with the recent project naming validation.
I did a slight change to combine name validation with workspace write permission validation instead of a messagebox pop up, which was a little intrusive.
ping @alexbruy
> Merge master, Update project name validation ux 

- Mergin/plugin.py
When plugin is loaded by `qgis_process` iface is not available, this cases errors on plugin load. We need to check whether iface is valid before accessing it in `__init__`, `initGui` and `unload`.
Fixes #493.
> do not assume iface is valid on plugin load (fix #493)

- Mergin/test/test_help.py
- Mergin/test/test_packaging.py
- Mergin/test/test_utils.py
- Mergin/test/test_validations.py
- Mergin/utils.py
> remove trailing slash from the mergin server URL (fix #491)

- Mergin/ui/ui_project_config.ui
> Tracking is not in beta now

- .github/workflows/packages.yml
Exclude tests from the package. Also make arifact a proper, ready to use plugin package.
Fixes #507.
> reduce size of an artifact and release package

- Mergin/ui/ui_sync_direction_page.ui
Fixes https://app.clickup.com/t/862kfkqr2
> fix opening documenation link

- Mergin/ui/ui_config_file_page.ui
In the last page of the wizard.
> fix opening a link

- Mergin/validation.py
Check if the layer has renderer
Fixes #530
> Fix check_svgs_embedded when there is non spatial layer

- Mergin/diff.py
> don't instantiate geodiff library at the module level, create it inside function (refs #504)

- Mergin/metadata.txt
- Mergin/processing/algs/create_diff.py
- Mergin/processing/algs/extract_local_changes.py
- docs/dev-docs.md
fix #562 
fix #563 
fix #564 
related to #196
> Fix errors 2024 1

- .github/workflows/run-test.yml
- docs/dev-docs.md
Latest docker image has some issues
> Fix CI tests

- .gitignore
Add ignore vscode files to .gitignore match existing configuration in mobile and server
> Add ignore vscode files to .gitignore

- docs/dev-docs.md
This PR add instructions to install the plugin locally on windows as well
I had to create this for a specific bug only happening on window
> update dev-docs.md on windows

- .github/workflows/packages.yml
- Mergin/project_selection_dialog.py
Bump python-api client to 0.10.0 and small fix related to imports
> Bump python-api client to 0.10.0

- .github/workflows/packages.yml
- Mergin/diff.py
- Mergin/diff_dialog.py
- Mergin/ui/ui_versions_viewer.ui
- Mergin/utils.py
- Mergin/version_viewer_dialog.py
This PR does a bunch of quality of life improvement and fixes for the history viewer:
* Pre-select latest version
* Fix treeview not available when fetching
* GUI fix for macos
* Fix various out of sync issue with UI/thread
* Fix align left with TreeView decoration
* Update CI
> Final adjustments for the history viewer 

- Mergin/metadata.txt
* Update version
* Update changelog
* Update tags
> Release 2025.1

- Mergin/configuration_dialog.py
- Mergin/plugin.py
- Mergin/ui/ui_project_config.ui
- Mergin/utils.py
Fixes #541 
Introduces new QGIS expression variable `mergin_user_email`
This PR is part of [Mergin Maps variables enhancement](https://github.com/MerginMaps/mobile/issues/3799), which introduces new QGIS expression variable `mergin_full_name` and changes the `mergin` prefix to `mm`.
> Improve MM QGIS expression variables

- Mergin/plugin.py
- Mergin/projects_manager.py
- Mergin/utils.py
* Make (mm|mergin)_project_* variable available again in the plugin
* remove mergin_project_owner
> Fix unavailable mergin_project_* variables and remove outdated mergin_project_owner variable

- Mergin/utils.py
confused `MM` with `mm` made the minutes swapped with months...
fix #706
> fix minutes swapped with months in display expression

- Mergin/create_project_wizard.py
- Mergin/projects_manager.py
Improve the error message if a project already exist is the same as if the project was deleted recently (< 7 days)
This PR has also the nice side effect to cleanup the local mergin project created before the server creation. which user had previously to manually delete if the server creation failed.
Fix #703
> Fix error message on recently deleted project

- Mergin/plugin.py
Fixes issue of trying to log user using SSO when QGIS is not fully ready and ends in error
Fixes #757 
Fixes #424
> only try to create mc if initialization of QGIS is complete

- Mergin/project_settings_widget.py
- Mergin/ui/ui_project_config.ui
Add settings for photo annotations to the project settings:
The settings is stored as:
```
Mergin/PhotoSketching/Enabled
```
> Photo Annotations

- Mergin/metadata.txt
- Mergin/project_settings_widget.py
- Mergin/ui/ui_project_config.ui
Add missing commits from **2025.3.1** branch to the master
> Add missing commits

- Mergin/ui/ui_project_config.ui
Cherry-picked from the previous release (we forgot to merge it to master).
> Make map sketching link clickable

- Mergin/project_settings_widget.py
With coming mobile release the photo sketching feature will be coming as a preview and will be opt-in.
> Change photo sketching to opt-in

- Mergin/validation.py
Fixes https://github.com/MerginMaps/qgis-plugin/issues/781
The path to SVG symbols can be defined relatively to project folder. In this case the validation was false positive. 
We convert the SVG symbol path to absolute before checking it is relative to project dir.
> Convert svg path to absolute before comparing to project dir

- Mergin/data_item.py
- Mergin/plugin.py
Divided plugin.py into data_item for cleaner code
> divided plugin.py into data_item

- Mergin/data_item.py
- Mergin/plugin.py
reverted changes of division and afterward divided plugin into data_item.py 
some comits was lost after dividing plugin [744a8b08dccbcf7b7ee0635a7375183cf501d7f1](https://github.com/MerginMaps/qgis-plugin/commit/744a8b08dccbcf7b7ee0635a7375183cf501d7f1)
i reverted changes and manulally divided it again 
(dowloaded zip and it is working)
> Refactor divide plugin

- Mergin/plugin.py
- Mergin/test/test_help.py
- Mergin/test/test_validations.py
- Mergin/utils.py
- Mergin/validation.py
Fixes #622 
The warning should display only when `Relative to Deafault Path` is selected from the dropdown (not only when there is some default path value)
> Local path warning
